FROM registry.centos.org/centos/centos:latest

LABEL RUN='docker run --rm --privileged $IMAGE /bin/tail -f /dev/null'

RUN useradd foo && touch /bin/ls && touch /bin/pwd && chown root:foo /bin/ls

RUN yum -y install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum -y install python2-pip && pip install six==1.11.0
